#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/laurel_sprout

PRODUCT_COPY_FILES += \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Codec_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Bluetooth_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Codec_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_General_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Global_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Handset_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Hdmi_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Headset_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_Speaker_cal.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/QRD_India/QRD_India_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_India/QRD_India_workspaceFile.qwsp \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/CFR_para.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/GpuKernelRepo.pb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/GpuKernelRepo.pb \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/LDC_packdata_xiaomi_F2_src1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi_F2_src1.dat \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/LDC_packdata_xiaomi_F2_src2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi_F2_src2.dat \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/beauty_ui9_intelligent_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beauty_ui9_intelligent_params.config \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/cameraconfig.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cameraconfig.txt \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/female_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_bg.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/female_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/female_icon.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/goldResult_582.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/goldResult_582.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/goldResult_586.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/goldResult_586.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_gc2375_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_gc2375_qtech_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_gc2375_qtech_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_gc2375_qtech_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx582_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx582_qtech_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx582_qtech_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx582_qtech_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx586_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx586_qtech_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx586_qtech_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx586_qtech_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx586_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx586_sunny_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_imx586_sunny_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_imx586_sunny_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_ov02a10_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_ov02a10_sunny_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_ov02a10_sunny_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_ov02a10_sunny_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5k4h7_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5k4h7_qtech_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5k4h7_qtech_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5k4h7_qtech_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5k4h7_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5k4h7_sunny_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5k4h7_sunny_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5k4h7_sunny_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_ofilm_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_ofilm_global_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_ofilm_global_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_ofilm_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_ofilm_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_sunny_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_sunny_global_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_sunny_global_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/laurus_s5kgd1_sunny_india_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/laurus_s5kgd1_sunny_india_chromatix.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/lf_facerank_model.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lf_facerank_model.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/libalfpc_tuning.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/libalfpc_tuning.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/male_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_bg.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/male_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/male_icon.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/model_back.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_back.dlc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/model_front.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_front.dlc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/score_bg.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_bg.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/score_icon.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/score_icon.png \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/sdm660_camera_global.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sdm660_camera_global.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/sdm660_camera_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sdm660_camera_india.xml \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/sdm_ys_32p_120_21_5_perturb50.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sdm_ys_32p_120_21_5_perturb50.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/ipa_fws.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipa_fws.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/bmi160_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bmi160_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_default_sensors.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_qrd_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_qrd_ak991x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_qrd_bmi160_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_qrd_bmi160_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_qrd_gpio129_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_qrd_gpio129_sx932x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_qrd_gpio131_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_qrd_gpio131_sx932x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/nicobar_qrd_stk3x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/nicobar_qrd_stk3x3x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_ccd_v2_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_walk.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_ccd_v3_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_walk.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/stk3x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/stk3x3x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/config/sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sx932x_0.json \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/thermal-engine-high.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-high.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/thermal-engine-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-map.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/thermal-engine-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-nolimits.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/thermal-engine-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-normal.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a610_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a610_zap.b00 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a610_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a610_zap.b01 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a610_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a610_zap.b02 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a610_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a610_zap.elf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a610_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a610_zap.mdt \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a612_rgmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a612_rgmu.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a618_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a618_gmu.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a630_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_gmu.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/a640_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a640_gmu.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_12_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_1.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/focaltech-ft3518-sumsung.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech-ft3518-sumsung.ini \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_cfg_group.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/gtx8_limits.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/gtx8_limits.csv \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/xiaomi/laurel_sprout/proprietary/vendor/lib/mibokeh_660_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/lib/mibokeh_660_opencl.bin

PRODUCT_PACKAGES += \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libseemore \
    libsensorslog \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsnsapi \
    libsnsdiaglog \
    libssc \
    vendor.qti.hardware.fingerprint@1.0 \
    camera.trinket \
    libFaceGrade \
    libSNPE \
    libVDClearShot \
    libVDSuperPhotoAPI \
    libXMFD_AgeGender \
    lib_lowlight \
    libactuator_ad5816g \
    libactuator_ad5823 \
    libactuator_ak7345 \
    libactuator_ak7371 \
    libactuator_bu64244gwz \
    libactuator_bu64297 \
    libactuator_dw9714 \
    libactuator_dw9716 \
    libactuator_dw9718s \
    libactuator_dw9761b \
    libactuator_dw9763 \
    libactuator_dw9763b \
    libactuator_dw9790a \
    libactuator_dw9800 \
    libactuator_dw9800_imx582 \
    libactuator_laurus_dw9800w_qtech \
    libactuator_lc898122 \
    libactuator_lc898212xd \
    libactuator_lc898212xd_qc2002 \
    libactuator_lc898217xc \
    libactuator_pseudo \
    libactuator_rohm_bu64243gwz \
    libalCFR \
    libalLDC \
    libalhLDC \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_portrait_lighting \
    libarcsoft_portrait_lighting_c \
    libarcsoft_supernight \
    libc++_shared \
    libcamera_scene \
    libchromatix_csidtg_common \
    libchromatix_csidtg_cpp_preview \
    libchromatix_csidtg_postproc \
    libchromatix_csidtg_preview \
    libchromatix_csidtg_zsl_preview \
    libchromatix_india_laurus_gc2375_qtech_HDR_cpp_snapshot \
    libchromatix_india_laurus_gc2375_qtech_HDR_snapshot \
    libchromatix_india_laurus_gc2375_qtech_HDR_zsl_preview_dw9800w \
    libchromatix_india_laurus_gc2375_qtech_common \
    libchromatix_india_laurus_gc2375_qtech_cpp_ds_chromatix \
    libchromatix_india_laurus_gc2375_qtech_cpp_liveshot \
    libchromatix_india_laurus_gc2375_qtech_cpp_preview \
    libchromatix_india_laurus_gc2375_qtech_cpp_snapshot \
    libchromatix_india_laurus_gc2375_qtech_cpp_us_chromatix \
    libchromatix_india_laurus_gc2375_qtech_cpp_video \
    libchromatix_india_laurus_gc2375_qtech_cpp_video_full \
    libchromatix_india_laurus_gc2375_qtech_cpp_video_weixin \
    libchromatix_india_laurus_gc2375_qtech_default_preview_bu64297 \
    libchromatix_india_laurus_gc2375_qtech_default_video \
    libchromatix_india_laurus_gc2375_qtech_default_video_bu64297 \
    libchromatix_india_laurus_gc2375_qtech_hht_cpp_snapshot \
    libchromatix_india_laurus_gc2375_qtech_panorama_cpp_snapshot \
    libchromatix_india_laurus_gc2375_qtech_panorama_snapshot \
    libchromatix_india_laurus_gc2375_qtech_panorama_zsl_preview_dw9800w \
    libchromatix_india_laurus_gc2375_qtech_postproc \
    libchromatix_india_laurus_gc2375_qtech_preview \
    libchromatix_india_laurus_gc2375_qtech_snapshot \
    libchromatix_india_laurus_gc2375_qtech_video_full \
    libchromatix_india_laurus_gc2375_qtech_video_weixin \
    libchromatix_india_laurus_gc2375_qtech_weixin_zsl_preview_dw9800w \
    libchromatix_india_laurus_gc2375_qtech_zsl_preview_bu64297 \
    libchromatix_india_laurus_gc2375_qtech_zsl_video_bu64297 \
    libchromatix_india_laurus_imx582_qtech_4k_preview_3a \
    libchromatix_india_laurus_imx582_qtech_4k_video_3a \
    libchromatix_india_laurus_imx582_qtech_common \
    libchromatix_india_laurus_imx582_qtech_cpp_hfr_120 \
    libchromatix_india_laurus_imx582_qtech_cpp_hfr_60 \
    libchromatix_india_laurus_imx582_qtech_cpp_hfr_90 \
    libchromatix_india_laurus_imx582_qtech_cpp_liveshot \
    libchromatix_india_laurus_imx582_qtech_cpp_preview \
    libchromatix_india_laurus_imx582_qtech_cpp_snapshot \
    libchromatix_india_laurus_imx582_qtech_cpp_video \
    libchromatix_india_laurus_imx582_qtech_cpp_video_4k \
    libchromatix_india_laurus_imx582_qtech_default_preview_3a \
    libchromatix_india_laurus_imx582_qtech_default_video \
    libchromatix_india_laurus_imx582_qtech_default_video_3a \
    libchromatix_india_laurus_imx582_qtech_default_video_4k \
    libchromatix_india_laurus_imx582_qtech_hfr_120 \
    libchromatix_india_laurus_imx582_qtech_hfr_120_3a \
    libchromatix_india_laurus_imx582_qtech_hfr_60 \
    libchromatix_india_laurus_imx582_qtech_hfr_60_3a \
    libchromatix_india_laurus_imx582_qtech_hfr_90 \
    libchromatix_india_laurus_imx582_qtech_hfr_90_3a \
    libchromatix_india_laurus_imx582_qtech_postproc \
    libchromatix_india_laurus_imx582_qtech_preview \
    libchromatix_india_laurus_imx582_qtech_snapshot \
    libchromatix_india_laurus_imx582_qtech_zsl_preview_3a \
    libchromatix_india_laurus_imx582_qtech_zsl_video_3a \
    libchromatix_india_laurus_imx586_qtech_48M_cpp_snapshot \
    libchromatix_india_laurus_imx586_qtech_48M_zsl_preview_dw9800w \
    libchromatix_india_laurus_imx586_qtech_HDR_zsl_preview_dw9800w \
    libchromatix_india_laurus_imx586_qtech_common \
    libchromatix_india_laurus_imx586_qtech_cpp_ds_chromatix \
    libchromatix_india_laurus_imx586_qtech_cpp_hfr_120 \
    libchromatix_india_laurus_imx586_qtech_cpp_hfr_60 \
    libchromatix_india_laurus_imx586_qtech_cpp_hfr_90 \
    libchromatix_india_laurus_imx586_qtech_cpp_liveshot \
    libchromatix_india_laurus_imx586_qtech_cpp_preview \
    libchromatix_india_laurus_imx586_qtech_cpp_snapshot \
    libchromatix_india_laurus_imx586_qtech_cpp_us_chromatix \
    libchromatix_india_laurus_imx586_qtech_cpp_video \
    libchromatix_india_laurus_imx586_qtech_cpp_video_full \
    libchromatix_india_laurus_imx586_qtech_cpp_video_weixin \
    libchromatix_india_laurus_imx586_qtech_default_preview_dw9800w \
    libchromatix_india_laurus_imx586_qtech_default_video \
    libchromatix_india_laurus_imx586_qtech_default_video_dw9800w \
    libchromatix_india_laurus_imx586_qtech_hfr_120 \
    libchromatix_india_laurus_imx586_qtech_hfr_120_dw9800w \
    libchromatix_india_laurus_imx586_qtech_hfr_60 \
    libchromatix_india_laurus_imx586_qtech_hfr_60_dw9800w \
    libchromatix_india_laurus_imx586_qtech_hfr_90 \
    libchromatix_india_laurus_imx586_qtech_hfr_90_dw9800w \
    libchromatix_india_laurus_imx586_qtech_hht_cpp_snapshot \
    libchromatix_india_laurus_imx586_qtech_postproc \
    libchromatix_india_laurus_imx586_qtech_preview \
    libchromatix_india_laurus_imx586_qtech_snapshot \
    libchromatix_india_laurus_imx586_qtech_video_full \
    libchromatix_india_laurus_imx586_qtech_video_weixin \
    libchromatix_india_laurus_imx586_qtech_weixin_zsl_preview_dw9800w \
    libchromatix_india_laurus_imx586_qtech_zsl_preview_dw9800w \
    libchromatix_india_laurus_imx586_qtech_zsl_video_dw9800w \
    libchromatix_india_laurus_ov02a10_sunny_HDR_cpp_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_HDR_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_HDR_zsl_preview_dw9800w \
    libchromatix_india_laurus_ov02a10_sunny_common \
    libchromatix_india_laurus_ov02a10_sunny_cpp_ds_chromatix \
    libchromatix_india_laurus_ov02a10_sunny_cpp_liveshot \
    libchromatix_india_laurus_ov02a10_sunny_cpp_preview \
    libchromatix_india_laurus_ov02a10_sunny_cpp_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_cpp_us_chromatix \
    libchromatix_india_laurus_ov02a10_sunny_cpp_video \
    libchromatix_india_laurus_ov02a10_sunny_cpp_video_full \
    libchromatix_india_laurus_ov02a10_sunny_cpp_video_weixin \
    libchromatix_india_laurus_ov02a10_sunny_default_preview_bu64297 \
    libchromatix_india_laurus_ov02a10_sunny_default_video \
    libchromatix_india_laurus_ov02a10_sunny_default_video_bu64297 \
    libchromatix_india_laurus_ov02a10_sunny_hht_cpp_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_panorama_cpp_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_panorama_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_panorama_zsl_preview_dw9800w \
    libchromatix_india_laurus_ov02a10_sunny_postproc \
    libchromatix_india_laurus_ov02a10_sunny_preview \
    libchromatix_india_laurus_ov02a10_sunny_snapshot \
    libchromatix_india_laurus_ov02a10_sunny_video_full \
    libchromatix_india_laurus_ov02a10_sunny_video_weixin \
    libchromatix_india_laurus_ov02a10_sunny_weixin_zsl_preview_dw9800w \
    libchromatix_india_laurus_ov02a10_sunny_zsl_preview_bu64297 \
    libchromatix_india_laurus_ov02a10_sunny_zsl_video_bu64297 \
    libchromatix_laurus_gc2375_qtech_HDR_cpp_snapshot \
    libchromatix_laurus_gc2375_qtech_HDR_snapshot \
    libchromatix_laurus_gc2375_qtech_HDR_zsl_preview_dw9800w \
    libchromatix_laurus_gc2375_qtech_common \
    libchromatix_laurus_gc2375_qtech_cpp_ds_chromatix \
    libchromatix_laurus_gc2375_qtech_cpp_liveshot \
    libchromatix_laurus_gc2375_qtech_cpp_preview \
    libchromatix_laurus_gc2375_qtech_cpp_snapshot \
    libchromatix_laurus_gc2375_qtech_cpp_us_chromatix \
    libchromatix_laurus_gc2375_qtech_cpp_video \
    libchromatix_laurus_gc2375_qtech_cpp_video_full \
    libchromatix_laurus_gc2375_qtech_cpp_video_weixin \
    libchromatix_laurus_gc2375_qtech_default_preview_bu64297 \
    libchromatix_laurus_gc2375_qtech_default_video \
    libchromatix_laurus_gc2375_qtech_default_video_bu64297 \
    libchromatix_laurus_gc2375_qtech_hht_cpp_snapshot \
    libchromatix_laurus_gc2375_qtech_panorama_cpp_snapshot \
    libchromatix_laurus_gc2375_qtech_panorama_snapshot \
    libchromatix_laurus_gc2375_qtech_panorama_zsl_preview_dw9800w \
    libchromatix_laurus_gc2375_qtech_postproc \
    libchromatix_laurus_gc2375_qtech_preview \
    libchromatix_laurus_gc2375_qtech_snapshot \
    libchromatix_laurus_gc2375_qtech_video_full \
    libchromatix_laurus_gc2375_qtech_video_weixin \
    libchromatix_laurus_gc2375_qtech_weixin_zsl_preview_dw9800w \
    libchromatix_laurus_gc2375_qtech_zsl_preview_bu64297 \
    libchromatix_laurus_gc2375_qtech_zsl_video_bu64297 \
    libchromatix_laurus_imx582_qtech_common \
    libchromatix_laurus_imx582_qtech_common_torch \
    libchromatix_laurus_imx582_qtech_cpp_ds_chromatix \
    libchromatix_laurus_imx582_qtech_cpp_hfr_120 \
    libchromatix_laurus_imx582_qtech_cpp_hfr_240 \
    libchromatix_laurus_imx582_qtech_cpp_hfr_60 \
    libchromatix_laurus_imx582_qtech_cpp_hfr_90 \
    libchromatix_laurus_imx582_qtech_cpp_liveshot \
    libchromatix_laurus_imx582_qtech_cpp_preview \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_12M \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_12M_hht \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_12M_sr \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_48M \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_48M_hht \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_HDR \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_panorama \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_portrait \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_sn \
    libchromatix_laurus_imx582_qtech_cpp_snapshot_torch \
    libchromatix_laurus_imx582_qtech_cpp_us_chromatix \
    libchromatix_laurus_imx582_qtech_cpp_video \
    libchromatix_laurus_imx582_qtech_cpp_video_1080P \
    libchromatix_laurus_imx582_qtech_cpp_video_4k \
    libchromatix_laurus_imx582_qtech_cpp_video_720P \
    libchromatix_laurus_imx582_qtech_cpp_video_weixin \
    libchromatix_laurus_imx582_qtech_default_preview \
    libchromatix_laurus_imx582_qtech_default_video \
    libchromatix_laurus_imx582_qtech_hfr_120 \
    libchromatix_laurus_imx582_qtech_hfr_240 \
    libchromatix_laurus_imx582_qtech_hfr_60 \
    libchromatix_laurus_imx582_qtech_hfr_90 \
    libchromatix_laurus_imx582_qtech_post_proc \
    libchromatix_laurus_imx582_qtech_preview \
    libchromatix_laurus_imx582_qtech_snapshot_12M \
    libchromatix_laurus_imx582_qtech_snapshot_12M_hht \
    libchromatix_laurus_imx582_qtech_snapshot_48M \
    libchromatix_laurus_imx582_qtech_snapshot_HDR \
    libchromatix_laurus_imx582_qtech_snapshot_panorama \
    libchromatix_laurus_imx582_qtech_snapshot_portrait \
    libchromatix_laurus_imx582_qtech_snapshot_sn \
    libchromatix_laurus_imx582_qtech_snapshot_torch \
    libchromatix_laurus_imx582_qtech_video \
    libchromatix_laurus_imx582_qtech_video_weixin \
    libchromatix_laurus_imx582_qtech_zsl_hfr_120 \
    libchromatix_laurus_imx582_qtech_zsl_hfr_240 \
    libchromatix_laurus_imx582_qtech_zsl_hfr_60 \
    libchromatix_laurus_imx582_qtech_zsl_hfr_90 \
    libchromatix_laurus_imx582_qtech_zsl_preview_12M \
    libchromatix_laurus_imx582_qtech_zsl_preview_48M \
    libchromatix_laurus_imx582_qtech_zsl_preview_HDR \
    libchromatix_laurus_imx582_qtech_zsl_preview_panorma \
    libchromatix_laurus_imx582_qtech_zsl_preview_portrait \
    libchromatix_laurus_imx582_qtech_zsl_preview_sn \
    libchromatix_laurus_imx582_qtech_zsl_preview_torch \
    libchromatix_laurus_imx582_qtech_zsl_video \
    libchromatix_laurus_imx582_qtech_zsl_video_4k \
    libchromatix_laurus_imx582_qtech_zsl_video_weixin \
    libchromatix_laurus_imx586_qtech_48M_cpp_snapshot \
    libchromatix_laurus_imx586_qtech_48M_zsl_preview_dw9800w \
    libchromatix_laurus_imx586_qtech_HDR_zsl_preview_dw9800w \
    libchromatix_laurus_imx586_qtech_common \
    libchromatix_laurus_imx586_qtech_cpp_ds_chromatix \
    libchromatix_laurus_imx586_qtech_cpp_hfr_120 \
    libchromatix_laurus_imx586_qtech_cpp_hfr_60 \
    libchromatix_laurus_imx586_qtech_cpp_hfr_90 \
    libchromatix_laurus_imx586_qtech_cpp_liveshot \
    libchromatix_laurus_imx586_qtech_cpp_preview \
    libchromatix_laurus_imx586_qtech_cpp_snapshot \
    libchromatix_laurus_imx586_qtech_cpp_us_chromatix \
    libchromatix_laurus_imx586_qtech_cpp_video \
    libchromatix_laurus_imx586_qtech_cpp_video_full \
    libchromatix_laurus_imx586_qtech_cpp_video_weixin \
    libchromatix_laurus_imx586_qtech_default_preview_dw9800w \
    libchromatix_laurus_imx586_qtech_default_video \
    libchromatix_laurus_imx586_qtech_default_video_dw9800w \
    libchromatix_laurus_imx586_qtech_hfr_120 \
    libchromatix_laurus_imx586_qtech_hfr_120_dw9800w \
    libchromatix_laurus_imx586_qtech_hfr_60 \
    libchromatix_laurus_imx586_qtech_hfr_60_dw9800w \
    libchromatix_laurus_imx586_qtech_hfr_90 \
    libchromatix_laurus_imx586_qtech_hfr_90_dw9800w \
    libchromatix_laurus_imx586_qtech_hht_cpp_snapshot \
    libchromatix_laurus_imx586_qtech_postproc \
    libchromatix_laurus_imx586_qtech_preview \
    libchromatix_laurus_imx586_qtech_snapshot \
    libchromatix_laurus_imx586_qtech_video_full \
    libchromatix_laurus_imx586_qtech_video_weixin \
    libchromatix_laurus_imx586_qtech_weixin_zsl_preview_dw9800w \
    libchromatix_laurus_imx586_qtech_zsl_preview_dw9800w \
    libchromatix_laurus_imx586_qtech_zsl_video_dw9800w \
    libchromatix_laurus_imx586_sunny_common \
    libchromatix_laurus_imx586_sunny_common_torch \
    libchromatix_laurus_imx586_sunny_cpp_ds_chromatix \
    libchromatix_laurus_imx586_sunny_cpp_hfr_120 \
    libchromatix_laurus_imx586_sunny_cpp_hfr_240 \
    libchromatix_laurus_imx586_sunny_cpp_hfr_60 \
    libchromatix_laurus_imx586_sunny_cpp_hfr_90 \
    libchromatix_laurus_imx586_sunny_cpp_liveshot \
    libchromatix_laurus_imx586_sunny_cpp_preview \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_12M \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_12M_hht \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_12M_sr \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_48M \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_48M_hht \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_HDR \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_panorama \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_portrait \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_sn \
    libchromatix_laurus_imx586_sunny_cpp_snapshot_torch \
    libchromatix_laurus_imx586_sunny_cpp_us_chromatix \
    libchromatix_laurus_imx586_sunny_cpp_video \
    libchromatix_laurus_imx586_sunny_cpp_video_1080P \
    libchromatix_laurus_imx586_sunny_cpp_video_4k \
    libchromatix_laurus_imx586_sunny_cpp_video_720P \
    libchromatix_laurus_imx586_sunny_cpp_video_weixin \
    libchromatix_laurus_imx586_sunny_default_preview \
    libchromatix_laurus_imx586_sunny_default_video \
    libchromatix_laurus_imx586_sunny_hfr_120 \
    libchromatix_laurus_imx586_sunny_hfr_240 \
    libchromatix_laurus_imx586_sunny_hfr_60 \
    libchromatix_laurus_imx586_sunny_hfr_90 \
    libchromatix_laurus_imx586_sunny_post_proc \
    libchromatix_laurus_imx586_sunny_preview \
    libchromatix_laurus_imx586_sunny_snapshot_12M \
    libchromatix_laurus_imx586_sunny_snapshot_12M_hht \
    libchromatix_laurus_imx586_sunny_snapshot_48M \
    libchromatix_laurus_imx586_sunny_snapshot_HDR \
    libchromatix_laurus_imx586_sunny_snapshot_panorama \
    libchromatix_laurus_imx586_sunny_snapshot_portrait \
    libchromatix_laurus_imx586_sunny_snapshot_sn \
    libchromatix_laurus_imx586_sunny_snapshot_torch \
    libchromatix_laurus_imx586_sunny_video \
    libchromatix_laurus_imx586_sunny_video_weixin \
    libchromatix_laurus_imx586_sunny_zsl_hfr_120 \
    libchromatix_laurus_imx586_sunny_zsl_hfr_240 \
    libchromatix_laurus_imx586_sunny_zsl_hfr_60 \
    libchromatix_laurus_imx586_sunny_zsl_hfr_90 \
    libchromatix_laurus_imx586_sunny_zsl_preview_12M \
    libchromatix_laurus_imx586_sunny_zsl_preview_48M \
    libchromatix_laurus_imx586_sunny_zsl_preview_HDR \
    libchromatix_laurus_imx586_sunny_zsl_preview_panorma \
    libchromatix_laurus_imx586_sunny_zsl_preview_portrait \
    libchromatix_laurus_imx586_sunny_zsl_preview_sn \
    libchromatix_laurus_imx586_sunny_zsl_preview_torch \
    libchromatix_laurus_imx586_sunny_zsl_video \
    libchromatix_laurus_imx586_sunny_zsl_video_4k \
    libchromatix_laurus_imx586_sunny_zsl_video_weixin \
    libchromatix_laurus_indian_imx586_sunny_common \
    libchromatix_laurus_indian_imx586_sunny_common_torch \
    libchromatix_laurus_indian_imx586_sunny_cpp_hfr_120 \
    libchromatix_laurus_indian_imx586_sunny_cpp_hfr_240 \
    libchromatix_laurus_indian_imx586_sunny_cpp_hfr_60 \
    libchromatix_laurus_indian_imx586_sunny_cpp_hfr_90 \
    libchromatix_laurus_indian_imx586_sunny_cpp_liveshot \
    libchromatix_laurus_indian_imx586_sunny_cpp_preview \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_12M \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_12M_hht \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_12M_sr \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_48M \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_48M_hht \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_HDR \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_panorama \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_portrait \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_sn \
    libchromatix_laurus_indian_imx586_sunny_cpp_snapshot_torch \
    libchromatix_laurus_indian_imx586_sunny_cpp_video \
    libchromatix_laurus_indian_imx586_sunny_cpp_video_1080P \
    libchromatix_laurus_indian_imx586_sunny_cpp_video_4k \
    libchromatix_laurus_indian_imx586_sunny_cpp_video_720P \
    libchromatix_laurus_indian_imx586_sunny_cpp_video_weixin \
    libchromatix_laurus_indian_imx586_sunny_hfr_120 \
    libchromatix_laurus_indian_imx586_sunny_hfr_240 \
    libchromatix_laurus_indian_imx586_sunny_hfr_60 \
    libchromatix_laurus_indian_imx586_sunny_hfr_90 \
    libchromatix_laurus_indian_imx586_sunny_post_proc \
    libchromatix_laurus_indian_imx586_sunny_preview \
    libchromatix_laurus_indian_imx586_sunny_snapshot_12M \
    libchromatix_laurus_indian_imx586_sunny_snapshot_48M \
    libchromatix_laurus_indian_imx586_sunny_snapshot_panorama \
    libchromatix_laurus_indian_imx586_sunny_snapshot_portrait \
    libchromatix_laurus_indian_imx586_sunny_snapshot_sn \
    libchromatix_laurus_indian_imx586_sunny_snapshot_torch \
    libchromatix_laurus_indian_imx586_sunny_video \
    libchromatix_laurus_indian_imx586_sunny_video_weixin \
    libchromatix_laurus_indian_imx586_sunny_zsl_hfr_120 \
    libchromatix_laurus_indian_imx586_sunny_zsl_hfr_240 \
    libchromatix_laurus_indian_imx586_sunny_zsl_hfr_60 \
    libchromatix_laurus_indian_imx586_sunny_zsl_hfr_90 \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_12M \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_48M \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_HDR \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_panorma \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_portrait \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_sn \
    libchromatix_laurus_indian_imx586_sunny_zsl_preview_torch \
    libchromatix_laurus_indian_imx586_sunny_zsl_video \
    libchromatix_laurus_indian_imx586_sunny_zsl_video_4k \
    libchromatix_laurus_indian_imx586_sunny_zsl_video_weixin \
    libchromatix_laurus_indian_s5k4h7_qtech_common \
    libchromatix_laurus_indian_s5k4h7_qtech_common_torch \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_liveshot \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_preview \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_snapshot \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_snapshot_HDR \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_snapshot_hht \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_snapshot_torch \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_video \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_video_1080P \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_video_720P \
    libchromatix_laurus_indian_s5k4h7_qtech_cpp_video_weixin \
    libchromatix_laurus_indian_s5k4h7_qtech_default_preview \
    libchromatix_laurus_indian_s5k4h7_qtech_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_qtech_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_qtech_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_qtech_post_proc \
    libchromatix_laurus_indian_s5k4h7_qtech_snapshot \
    libchromatix_laurus_indian_s5k4h7_qtech_snapshot_torch \
    libchromatix_laurus_indian_s5k4h7_qtech_video \
    libchromatix_laurus_indian_s5k4h7_qtech_video_weixin \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_preview \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_preview_HDR \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_preview_torch \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_video \
    libchromatix_laurus_indian_s5k4h7_qtech_zsl_video_weixin \
    libchromatix_laurus_indian_s5k4h7_sunny_common \
    libchromatix_laurus_indian_s5k4h7_sunny_common_torch \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_liveshot \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_preview \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_snapshot \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_snapshot_HDR \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_snapshot_hht \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_snapshot_torch \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_video \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_video_1080P \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_video_720P \
    libchromatix_laurus_indian_s5k4h7_sunny_cpp_video_weixin \
    libchromatix_laurus_indian_s5k4h7_sunny_default_preview \
    libchromatix_laurus_indian_s5k4h7_sunny_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_sunny_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_sunny_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_sunny_post_proc \
    libchromatix_laurus_indian_s5k4h7_sunny_snapshot \
    libchromatix_laurus_indian_s5k4h7_sunny_snapshot_torch \
    libchromatix_laurus_indian_s5k4h7_sunny_video \
    libchromatix_laurus_indian_s5k4h7_sunny_video_weixin \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_hfr_120 \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_hfr_60 \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_hfr_90 \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_preview \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_preview_HDR \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_preview_torch \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_video \
    libchromatix_laurus_indian_s5k4h7_sunny_zsl_video_weixin \
    libchromatix_laurus_ov02a10_sunny_HDR_cpp_snapshot \
    libchromatix_laurus_ov02a10_sunny_HDR_snapshot \
    libchromatix_laurus_ov02a10_sunny_HDR_zsl_preview_dw9800w \
    libchromatix_laurus_ov02a10_sunny_common \
    libchromatix_laurus_ov02a10_sunny_cpp_ds_chromatix \
    libchromatix_laurus_ov02a10_sunny_cpp_liveshot \
    libchromatix_laurus_ov02a10_sunny_cpp_preview \
    libchromatix_laurus_ov02a10_sunny_cpp_snapshot \
    libchromatix_laurus_ov02a10_sunny_cpp_us_chromatix \
    libchromatix_laurus_ov02a10_sunny_cpp_video \
    libchromatix_laurus_ov02a10_sunny_cpp_video_full \
    libchromatix_laurus_ov02a10_sunny_cpp_video_weixin \
    libchromatix_laurus_ov02a10_sunny_default_preview_bu64297 \
    libchromatix_laurus_ov02a10_sunny_default_video \
    libchromatix_laurus_ov02a10_sunny_default_video_bu64297 \
    libchromatix_laurus_ov02a10_sunny_hht_cpp_snapshot \
    libchromatix_laurus_ov02a10_sunny_panorama_cpp_snapshot \
    libchromatix_laurus_ov02a10_sunny_panorama_snapshot \
    libchromatix_laurus_ov02a10_sunny_panorama_zsl_preview_dw9800w \
    libchromatix_laurus_ov02a10_sunny_postproc \
    libchromatix_laurus_ov02a10_sunny_preview \
    libchromatix_laurus_ov02a10_sunny_snapshot \
    libchromatix_laurus_ov02a10_sunny_video_full \
    libchromatix_laurus_ov02a10_sunny_video_weixin \
    libchromatix_laurus_ov02a10_sunny_weixin_zsl_preview_dw9800w \
    libchromatix_laurus_ov02a10_sunny_zsl_preview_bu64297 \
    libchromatix_laurus_ov02a10_sunny_zsl_video_bu64297 \
    libchromatix_laurus_s5k4h7_qtech_common \
    libchromatix_laurus_s5k4h7_qtech_common_torch \
    libchromatix_laurus_s5k4h7_qtech_cpp_ds_chromatix \
    libchromatix_laurus_s5k4h7_qtech_cpp_hfr_120 \
    libchromatix_laurus_s5k4h7_qtech_cpp_hfr_60 \
    libchromatix_laurus_s5k4h7_qtech_cpp_hfr_90 \
    libchromatix_laurus_s5k4h7_qtech_cpp_liveshot \
    libchromatix_laurus_s5k4h7_qtech_cpp_preview \
    libchromatix_laurus_s5k4h7_qtech_cpp_snapshot \
    libchromatix_laurus_s5k4h7_qtech_cpp_snapshot_HDR \
    libchromatix_laurus_s5k4h7_qtech_cpp_snapshot_hht \
    libchromatix_laurus_s5k4h7_qtech_cpp_snapshot_torch \
    libchromatix_laurus_s5k4h7_qtech_cpp_us_chromatix \
    libchromatix_laurus_s5k4h7_qtech_cpp_video \
    libchromatix_laurus_s5k4h7_qtech_cpp_video_1080P \
    libchromatix_laurus_s5k4h7_qtech_cpp_video_720P \
    libchromatix_laurus_s5k4h7_qtech_cpp_video_weixin \
    libchromatix_laurus_s5k4h7_qtech_default_preview \
    libchromatix_laurus_s5k4h7_qtech_default_video \
    libchromatix_laurus_s5k4h7_qtech_hfr_120 \
    libchromatix_laurus_s5k4h7_qtech_hfr_60 \
    libchromatix_laurus_s5k4h7_qtech_hfr_90 \
    libchromatix_laurus_s5k4h7_qtech_post_proc \
    libchromatix_laurus_s5k4h7_qtech_preview \
    libchromatix_laurus_s5k4h7_qtech_snapshot \
    libchromatix_laurus_s5k4h7_qtech_snapshot_HDR \
    libchromatix_laurus_s5k4h7_qtech_snapshot_hht \
    libchromatix_laurus_s5k4h7_qtech_snapshot_torch \
    libchromatix_laurus_s5k4h7_qtech_video \
    libchromatix_laurus_s5k4h7_qtech_video_weixin \
    libchromatix_laurus_s5k4h7_qtech_zsl_hfr_120 \
    libchromatix_laurus_s5k4h7_qtech_zsl_hfr_60 \
    libchromatix_laurus_s5k4h7_qtech_zsl_hfr_90 \
    libchromatix_laurus_s5k4h7_qtech_zsl_preview \
    libchromatix_laurus_s5k4h7_qtech_zsl_preview_HDR \
    libchromatix_laurus_s5k4h7_qtech_zsl_preview_torch \
    libchromatix_laurus_s5k4h7_qtech_zsl_video \
    libchromatix_laurus_s5k4h7_qtech_zsl_video_weixin \
    libchromatix_laurus_s5k4h7_sunny_common \
    libchromatix_laurus_s5k4h7_sunny_common_torch \
    libchromatix_laurus_s5k4h7_sunny_cpp_ds_chromatix \
    libchromatix_laurus_s5k4h7_sunny_cpp_hfr_120 \
    libchromatix_laurus_s5k4h7_sunny_cpp_hfr_60 \
    libchromatix_laurus_s5k4h7_sunny_cpp_hfr_90 \
    libchromatix_laurus_s5k4h7_sunny_cpp_liveshot \
    libchromatix_laurus_s5k4h7_sunny_cpp_preview \
    libchromatix_laurus_s5k4h7_sunny_cpp_snapshot \
    libchromatix_laurus_s5k4h7_sunny_cpp_snapshot_HDR \
    libchromatix_laurus_s5k4h7_sunny_cpp_snapshot_hht \
    libchromatix_laurus_s5k4h7_sunny_cpp_snapshot_torch \
    libchromatix_laurus_s5k4h7_sunny_cpp_us_chromatix \
    libchromatix_laurus_s5k4h7_sunny_cpp_video \
    libchromatix_laurus_s5k4h7_sunny_cpp_video_1080P \
    libchromatix_laurus_s5k4h7_sunny_cpp_video_720P \
    libchromatix_laurus_s5k4h7_sunny_cpp_video_weixin \
    libchromatix_laurus_s5k4h7_sunny_default_preview \
    libchromatix_laurus_s5k4h7_sunny_default_video \
    libchromatix_laurus_s5k4h7_sunny_hfr_120 \
    libchromatix_laurus_s5k4h7_sunny_hfr_60 \
    libchromatix_laurus_s5k4h7_sunny_hfr_90 \
    libchromatix_laurus_s5k4h7_sunny_post_proc \
    libchromatix_laurus_s5k4h7_sunny_preview \
    libchromatix_laurus_s5k4h7_sunny_snapshot \
    libchromatix_laurus_s5k4h7_sunny_snapshot_HDR \
    libchromatix_laurus_s5k4h7_sunny_snapshot_hht \
    libchromatix_laurus_s5k4h7_sunny_snapshot_torch \
    libchromatix_laurus_s5k4h7_sunny_video \
    libchromatix_laurus_s5k4h7_sunny_video_weixin \
    libchromatix_laurus_s5k4h7_sunny_zsl_hfr_120 \
    libchromatix_laurus_s5k4h7_sunny_zsl_hfr_60 \
    libchromatix_laurus_s5k4h7_sunny_zsl_hfr_90 \
    libchromatix_laurus_s5k4h7_sunny_zsl_preview \
    libchromatix_laurus_s5k4h7_sunny_zsl_preview_HDR \
    libchromatix_laurus_s5k4h7_sunny_zsl_preview_torch \
    libchromatix_laurus_s5k4h7_sunny_zsl_video \
    libchromatix_laurus_s5k4h7_sunny_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_common \
    libchromatix_laurus_s5kgd1_ofilm_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_cpp_liveshot \
    libchromatix_laurus_s5kgd1_ofilm_cpp_preview \
    libchromatix_laurus_s5kgd1_ofilm_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_ofilm_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_ofilm_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_ofilm_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_ofilm_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_cpp_video \
    libchromatix_laurus_s5kgd1_ofilm_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_ofilm_cpp_video_720P \
    libchromatix_laurus_s5kgd1_ofilm_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_default_preview \
    libchromatix_laurus_s5kgd1_ofilm_default_video \
    libchromatix_laurus_s5kgd1_ofilm_global_common \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_liveshot \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_preview \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_video \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_video_720P \
    libchromatix_laurus_s5kgd1_ofilm_global_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_global_default_preview \
    libchromatix_laurus_s5kgd1_ofilm_global_default_video \
    libchromatix_laurus_s5kgd1_ofilm_global_post_proc \
    libchromatix_laurus_s5kgd1_ofilm_global_preview \
    libchromatix_laurus_s5kgd1_ofilm_global_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_global_snapshot \
    libchromatix_laurus_s5kgd1_ofilm_global_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_global_video \
    libchromatix_laurus_s5kgd1_ofilm_global_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_preview \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_video \
    libchromatix_laurus_s5kgd1_ofilm_global_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_india_common \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_liveshot \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_preview \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_video \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_video_720P \
    libchromatix_laurus_s5kgd1_ofilm_india_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_india_default_preview \
    libchromatix_laurus_s5kgd1_ofilm_india_default_video \
    libchromatix_laurus_s5kgd1_ofilm_india_post_proc \
    libchromatix_laurus_s5kgd1_ofilm_india_preview \
    libchromatix_laurus_s5kgd1_ofilm_india_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_india_snapshot \
    libchromatix_laurus_s5kgd1_ofilm_india_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_india_video \
    libchromatix_laurus_s5kgd1_ofilm_india_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_preview \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_video \
    libchromatix_laurus_s5kgd1_ofilm_india_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_post_proc \
    libchromatix_laurus_s5kgd1_ofilm_preview \
    libchromatix_laurus_s5kgd1_ofilm_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_snapshot \
    libchromatix_laurus_s5kgd1_ofilm_snapshot_HDR \
    libchromatix_laurus_s5kgd1_ofilm_video \
    libchromatix_laurus_s5kgd1_ofilm_video_weixin \
    libchromatix_laurus_s5kgd1_ofilm_zsl_preview \
    libchromatix_laurus_s5kgd1_ofilm_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_ofilm_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_ofilm_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_ofilm_zsl_video \
    libchromatix_laurus_s5kgd1_ofilm_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_common \
    libchromatix_laurus_s5kgd1_sunny_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_sunny_cpp_liveshot \
    libchromatix_laurus_s5kgd1_sunny_cpp_preview \
    libchromatix_laurus_s5kgd1_sunny_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_sunny_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_sunny_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_sunny_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_sunny_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_sunny_cpp_video \
    libchromatix_laurus_s5kgd1_sunny_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_sunny_cpp_video_720P \
    libchromatix_laurus_s5kgd1_sunny_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_default_preview \
    libchromatix_laurus_s5kgd1_sunny_default_video \
    libchromatix_laurus_s5kgd1_sunny_global_common \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_liveshot \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_preview \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_video \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_video_720P \
    libchromatix_laurus_s5kgd1_sunny_global_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_global_default_preview \
    libchromatix_laurus_s5kgd1_sunny_global_default_video \
    libchromatix_laurus_s5kgd1_sunny_global_post_proc \
    libchromatix_laurus_s5kgd1_sunny_global_preview \
    libchromatix_laurus_s5kgd1_sunny_global_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_global_snapshot \
    libchromatix_laurus_s5kgd1_sunny_global_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_global_video \
    libchromatix_laurus_s5kgd1_sunny_global_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_preview \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_video \
    libchromatix_laurus_s5kgd1_sunny_global_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_india_common \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_ds_chromatix \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_liveshot \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_preview \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_snapshot_32M \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_snapshot_8M \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_snapshot_8M_hht \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_snapshot_panorama \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_us_chromatix \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_video \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_video_1080P \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_video_720P \
    libchromatix_laurus_s5kgd1_sunny_india_cpp_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_india_default_preview \
    libchromatix_laurus_s5kgd1_sunny_india_default_video \
    libchromatix_laurus_s5kgd1_sunny_india_post_proc \
    libchromatix_laurus_s5kgd1_sunny_india_preview \
    libchromatix_laurus_s5kgd1_sunny_india_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_india_snapshot \
    libchromatix_laurus_s5kgd1_sunny_india_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_india_video \
    libchromatix_laurus_s5kgd1_sunny_india_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_preview \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_video \
    libchromatix_laurus_s5kgd1_sunny_india_zsl_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_post_proc \
    libchromatix_laurus_s5kgd1_sunny_preview \
    libchromatix_laurus_s5kgd1_sunny_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_snapshot \
    libchromatix_laurus_s5kgd1_sunny_snapshot_HDR \
    libchromatix_laurus_s5kgd1_sunny_video \
    libchromatix_laurus_s5kgd1_sunny_video_weixin \
    libchromatix_laurus_s5kgd1_sunny_zsl_preview \
    libchromatix_laurus_s5kgd1_sunny_zsl_preview_HDR \
    libchromatix_laurus_s5kgd1_sunny_zsl_preview_faceunlock \
    libchromatix_laurus_s5kgd1_sunny_zsl_preview_panorama \
    libchromatix_laurus_s5kgd1_sunny_zsl_video \
    libchromatix_laurus_s5kgd1_sunny_zsl_video_weixin \
    libdepthmapwrapper \
    libdng_sdkvendor \
    libflash_pmic \
    libft2vendor \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmialgo_sd \
    libmibokeh_660 \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_bokeh \
    libmmcamera_csidtg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_dw9761b_2d_eeprom \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_interface \
    libmmcamera_irs1645 \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_laurus_gc2375_qtech \
    libmmcamera_laurus_imx582_qtech \
    libmmcamera_laurus_imx586_qtech \
    libmmcamera_laurus_imx586_sunny \
    libmmcamera_laurus_ofilm_s5kgd1_eeprom \
    libmmcamera_laurus_ov02a10_sunny \
    libmmcamera_laurus_qtech_imx582_eeprom \
    libmmcamera_laurus_qtech_imx586_eeprom \
    libmmcamera_laurus_qtech_s5k4h7_eeprom \
    libmmcamera_laurus_s5k4h7_qtech \
    libmmcamera_laurus_s5k4h7_sunny \
    libmmcamera_laurus_s5kgd1_ofilm \
    libmmcamera_laurus_s5kgd1_sunny \
    libmmcamera_laurus_sunny_imx586_eeprom \
    libmmcamera_laurus_sunny_s5k4h7_eeprom \
    libmmcamera_laurus_sunny_s5kgd1_eeprom \
    libmmcamera_le2464c_eeprom \
    libmmcamera_le2464c_master_eeprom \
    libmmcamera_m24c64s_eeprom \
    libmmcamera_onsemi_cat24c16_eeprom \
    libmmcamera_onsemi_cat24c32_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_qtech_f3l8yam_eeprom \
    libmmcamera_qtech_f5670bq_eeprom \
    libmmcamera_quadracfa \
    libmmcamera_rohm_brcg064gwz_3_eeprom \
    libmmcamera_sat_test_lib \
    libmmcamera_stillmore_lib \
    libmmcamera_sunny_8865_eeprom \
    libmmcamera_sunny_q13v06k_eeprom \
    libmmcamera_sunny_q5v41b_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_truly_cma481_eeprom \
    libmmcamera_truly_cmb433_eeprom \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libois_bu63165 \
    libois_lc898122 \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libsymphony-cpu \
    libsymphonypower \
    libvideoutils \
    libvidhance \
    miwatermark \
    fingerprint.goodix_fod.default \
    vendor.qti.hardware.sensorscalibrate@1.0-impl \
    libgf_hal \
    libsensorcal \
    libsns_registry_skel \
    libssc_default_listener \
    libvendor.goodix.hardware.biometrics.fingerprint@2.1 \
    sensors.ssc \
    vendor.qti.hardware.fingerprintext@1.0 \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    misound_res \
    cnss-daemon \
    vendor.qti.hardware.sensorscalibrate@1.0-service \
    sensors.qti
